language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - pypy
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  make coverage
notifications:
  email:
    - kimmo.brunfeldt+urltoimage@futurice.com
deploy:
  # https://github.com/travis-ci/dpl#pypi
  provider: pypi
  distributions: 'sdist wheel'
  user: kimmobrunfeldt
  password:
    secure: WiNJUoJYaoDOep6V1aiMLMIH801+W7s11qqcYRKvxHWJyIcztTJA4YQmABxLjjDZPi9ljUpg2jRYzxuE83qQstWo/M6zkw7QnK2ahjzNTl/jzCmYGNYIgHiH0TYQzk0v5dtkQHjElVwq6uz6JzO/M8Fge/teUJUoeYI5EEOQ+8Y=
  on:
    tags: true
after_success:
  - coveralls --verbose

